/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import View.MenuAbout;
import View.MenuDashboard;
import View.MenuGuru;
import View.MenuJurusan;
import View.MenuKelas;
import View.MenuSiswa;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author ACER
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_Dashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pn_Jurusan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pn_Guru = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pn_Kelas = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pn_Siswa = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pn_About = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pn_Logout = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        pn_Kanan = new javax.swing.JPanel();
        pn_Atas = new javax.swing.JPanel();
        lb_Close = new javax.swing.JLabel();
        pn_Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_Kiri.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Education.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alumni");

        pn_Dashboard.setBackground(new java.awt.Color(0, 102, 255));
        pn_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_DashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_DashboardMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Dashboard.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DASHBOARD");

        javax.swing.GroupLayout pn_DashboardLayout = new javax.swing.GroupLayout(pn_Dashboard);
        pn_Dashboard.setLayout(pn_DashboardLayout);
        pn_DashboardLayout.setHorizontalGroup(
            pn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_DashboardLayout.setVerticalGroup(
            pn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_Jurusan.setBackground(new java.awt.Color(0, 102, 255));
        pn_Jurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_JurusanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_JurusanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_JurusanMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Building.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("JURUSAN");

        javax.swing.GroupLayout pn_JurusanLayout = new javax.swing.GroupLayout(pn_Jurusan);
        pn_Jurusan.setLayout(pn_JurusanLayout);
        pn_JurusanLayout.setHorizontalGroup(
            pn_JurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_JurusanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_JurusanLayout.setVerticalGroup(
            pn_JurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_JurusanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_JurusanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_Guru.setBackground(new java.awt.Color(0, 102, 255));
        pn_Guru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_GuruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_GuruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_GuruMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Teacher.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("GURU");

        javax.swing.GroupLayout pn_GuruLayout = new javax.swing.GroupLayout(pn_Guru);
        pn_Guru.setLayout(pn_GuruLayout);
        pn_GuruLayout.setHorizontalGroup(
            pn_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_GuruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_GuruLayout.setVerticalGroup(
            pn_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_GuruLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_GuruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_Kelas.setBackground(new java.awt.Color(0, 102, 255));
        pn_Kelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_KelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_KelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_KelasMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Whiteboard.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("KELAS");

        javax.swing.GroupLayout pn_KelasLayout = new javax.swing.GroupLayout(pn_Kelas);
        pn_Kelas.setLayout(pn_KelasLayout);
        pn_KelasLayout.setHorizontalGroup(
            pn_KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_KelasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_KelasLayout.setVerticalGroup(
            pn_KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_KelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_KelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_Siswa.setBackground(new java.awt.Color(0, 102, 255));
        pn_Siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_SiswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_SiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_SiswaMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Manager.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SISWA");

        javax.swing.GroupLayout pn_SiswaLayout = new javax.swing.GroupLayout(pn_Siswa);
        pn_Siswa.setLayout(pn_SiswaLayout);
        pn_SiswaLayout.setHorizontalGroup(
            pn_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_SiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_SiswaLayout.setVerticalGroup(
            pn_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_SiswaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_SiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_About.setBackground(new java.awt.Color(0, 102, 255));
        pn_About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_AboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_AboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_AboutMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/About.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ABOUT");

        javax.swing.GroupLayout pn_AboutLayout = new javax.swing.GroupLayout(pn_About);
        pn_About.setLayout(pn_AboutLayout);
        pn_AboutLayout.setHorizontalGroup(
            pn_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_AboutLayout.setVerticalGroup(
            pn_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_AboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_Logout.setBackground(new java.awt.Color(0, 102, 255));
        pn_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_LogoutMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logout.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("LOGOUT");

        javax.swing.GroupLayout pn_LogoutLayout = new javax.swing.GroupLayout(pn_Logout);
        pn_Logout.setLayout(pn_LogoutLayout);
        pn_LogoutLayout.setHorizontalGroup(
            pn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_LogoutLayout.setVerticalGroup(
            pn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pn_KiriLayout = new javax.swing.GroupLayout(pn_Kiri);
        pn_Kiri.setLayout(pn_KiriLayout);
        pn_KiriLayout.setHorizontalGroup(
            pn_KiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_KiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_KiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_KiriLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pn_Jurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_Guru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_Kelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_Siswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pn_KiriLayout.setVerticalGroup(
            pn_KiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_KiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_KiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86)
                .addComponent(pn_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Guru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Siswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_About, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        getContentPane().add(pn_Kiri, java.awt.BorderLayout.LINE_START);

        pn_Kanan.setLayout(new java.awt.BorderLayout());

        pn_Atas.setBackground(new java.awt.Color(102, 102, 102));

        lb_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Close Window.png"))); // NOI18N
        lb_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_CloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_AtasLayout = new javax.swing.GroupLayout(pn_Atas);
        pn_Atas.setLayout(pn_AtasLayout);
        pn_AtasLayout.setHorizontalGroup(
            pn_AtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_AtasLayout.createSequentialGroup()
                .addContainerGap(1130, Short.MAX_VALUE)
                .addComponent(lb_Close)
                .addContainerGap())
        );
        pn_AtasLayout.setVerticalGroup(
            pn_AtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_AtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_Kanan.add(pn_Atas, java.awt.BorderLayout.PAGE_START);

        pn_Content.setLayout(new java.awt.BorderLayout());
        pn_Kanan.add(pn_Content, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_Kanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pn_DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DashboardMouseEntered
        pn_Dashboard.setBackground(new Color(0, 51, 255));
    }//GEN-LAST:event_pn_DashboardMouseEntered

    private void pn_DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DashboardMouseExited
        pn_Dashboard.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_pn_DashboardMouseExited

    private void pn_DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_DashboardMouseClicked
        pn_Content.removeAll();
        pn_Content.add(new MenuDashboard());
        pn_Content.repaint();
        pn_Content.revalidate();
    }//GEN-LAST:event_pn_DashboardMouseClicked

    private void pn_JurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_JurusanMouseClicked
        pn_Content.removeAll();
        pn_Content.add(new MenuJurusan());
        pn_Content.repaint();
        pn_Content.revalidate();
    }//GEN-LAST:event_pn_JurusanMouseClicked

    private void pn_JurusanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_JurusanMouseEntered
        pn_Jurusan.setBackground(new Color(0, 51, 255));
    }//GEN-LAST:event_pn_JurusanMouseEntered

    private void pn_JurusanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_JurusanMouseExited
        pn_Jurusan.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_pn_JurusanMouseExited

    private void pn_GuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_GuruMouseClicked
        pn_Content.removeAll();
        pn_Content.add(new MenuGuru());
        pn_Content.repaint();
        pn_Content.revalidate();
    }//GEN-LAST:event_pn_GuruMouseClicked

    private void pn_GuruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_GuruMouseEntered
        pn_Guru.setBackground(new Color(0, 51, 255));
    }//GEN-LAST:event_pn_GuruMouseEntered

    private void pn_GuruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_GuruMouseExited
        pn_Guru.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_pn_GuruMouseExited

    private void pn_KelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_KelasMouseClicked
        pn_Content.removeAll();
        pn_Content.add(new MenuKelas());
        pn_Content.repaint();
        pn_Content.revalidate();
    }//GEN-LAST:event_pn_KelasMouseClicked

    private void pn_KelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_KelasMouseEntered
        pn_Kelas.setBackground(new Color(0, 51, 255));
    }//GEN-LAST:event_pn_KelasMouseEntered

    private void pn_KelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_KelasMouseExited
        pn_Kelas.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_pn_KelasMouseExited

    private void pn_SiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_SiswaMouseClicked
        pn_Content.removeAll();
        pn_Content.add(new MenuSiswa());
        pn_Content.repaint();
        pn_Content.revalidate();
    }//GEN-LAST:event_pn_SiswaMouseClicked

    private void pn_SiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_SiswaMouseEntered
        pn_Siswa.setBackground(new Color(0, 51, 255));
    }//GEN-LAST:event_pn_SiswaMouseEntered

    private void pn_SiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_SiswaMouseExited
        pn_Siswa.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_pn_SiswaMouseExited

    private void pn_AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_AboutMouseClicked
        pn_Content.removeAll();
        pn_Content.add(new MenuAbout());
        pn_Content.repaint();
        pn_Content.revalidate();
    }//GEN-LAST:event_pn_AboutMouseClicked

    private void pn_AboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_AboutMouseEntered
        pn_About.setBackground(new Color(0, 51, 255));
    }//GEN-LAST:event_pn_AboutMouseEntered

    private void pn_AboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_AboutMouseExited
        pn_About.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_pn_AboutMouseExited

    private void pn_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LogoutMouseClicked
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_pn_LogoutMouseClicked

    private void pn_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LogoutMouseEntered
        pn_Logout.setBackground(new Color(0, 51, 255));
    }//GEN-LAST:event_pn_LogoutMouseEntered

    private void pn_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LogoutMouseExited
        pn_Logout.setBackground(new Color(0, 102, 255));
    }//GEN-LAST:event_pn_LogoutMouseExited

    private void lb_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_CloseMouseClicked
        dispose();
    }//GEN-LAST:event_lb_CloseMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pn_Content.removeAll();
        pn_Content.add(new MenuDashboard());
        pn_Content.repaint();
        pn_Content.revalidate();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_Close;
    private javax.swing.JPanel pn_About;
    private javax.swing.JPanel pn_Atas;
    private javax.swing.JPanel pn_Content;
    private javax.swing.JPanel pn_Dashboard;
    private javax.swing.JPanel pn_Guru;
    private javax.swing.JPanel pn_Jurusan;
    private javax.swing.JPanel pn_Kanan;
    private javax.swing.JPanel pn_Kelas;
    private javax.swing.JPanel pn_Kiri;
    private javax.swing.JPanel pn_Logout;
    private javax.swing.JPanel pn_Siswa;
    // End of variables declaration//GEN-END:variables
}
